### ISSUE TITLE
Cannot add 'mollie' as payment method

### ISSUE THREAD

**Issue by bwydoogh** [axelvnk/SyliusMolliePayumBundle#7]
Hi. 

I followed all instructions (including the `INSERT` query in the gateway table). But no luck... I cannot add 'mollie' as payment method: see attached screenshot. Using **Sylius 1.0.6** (the latest).

! Notice that I am working in **development** mode.
! Notice that I am using **nl_BE as locale**.
Don't know if that might be the reason why this is not working (but I doubt - see the EDIT below).

![image](https://user-images.githubusercontent.com/1235571/34380040-ed5af4ae-eafe-11e7-94cc-e08e4de2bb50.png)

Any advice?

--

**EDIT**: got it up and running by manually inserting the necessary records in the `sylius_payment_method` table (_and others_). Don't know if your installation instructions are valid for Sylius installations prior to 1.0.6 (as that is the version I am currently using).

**Comment by axelvnk** [comment]
@bwydoogh Sorry for the late reply. But yeah, my installations instructions are for 1.0@beta. I really need to put some work in and make some adjustments for 1.0.
